### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by casolorz**
Upgraded to Android Studio 3.0.1
Fixed the issues from January 31st 2018
Added API Level to comments.

### CODE REVIEW

**Comment by casolorz** [comment]
Just noticed that with this fix, the comments section sometimes crashes. Seeing the error I'm guessing it is an issue from updating the target sdk. I can take a look at it again next week.

**Comment by nelenkov** [comment]
Thanks!

**Comment by casolorz** [comment]
You might want to wait before releasing it. The comments section keeps crashing on me, fairly unpredictable when it will crash. I can take a deeper look but won't be till next week.

**Comment by nelenkov** [comment]
I sometimes get this, so looks like some data is missing in some cases (the API level?):
```
02-01 10:42:00.712 22099 22156 D ACRA    : Wait for Toast + worker ended. Kill Application ? true
02-01 10:42:00.712 22099 22156 E ACRA    : com.github.andlyticsproject fatal error : Attempt to invoke virtual method 'void android.view.View.setVisibility(int)' on a null object reference
02-01 10:42:00.712 22099 22156 E ACRA    : java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setVisibility(int)' on a null object reference
02-01 10:42:00.712 22099 22156 E ACRA    : 	at com.github.andlyticsproject.CommentsListAdapter.getChildView(CommentsListAdapter.java:128)
02-01 10:42:00.712 22099 22156 E ACRA    : 	at android.widget.ExpandableListConnector.getView(ExpandableListConnector.java:451)
02-01 10:42:00.712 22099 22156 E ACRA    : 	at android.widget.HeaderViewListAdapter.getView(HeaderViewListAdapter.java:220)

```

**Comment by casolorz** [comment]
Will fix that in a minute.

**Pull request merged**
