### PR TITLE
Preview strings with variable names and example values.

### PR DESCRIPTION
**Pull request by johnjohndoe**
I wrapped variables in strings into XLIFF to facilitate preview renderings in Android Studio which show either the variable name or an example value.
Here are two example screenshots:

example1
example2

### CODE REVIEW

**Comment by willlunniss** [comment]
Don't suppose if you know if this will play nice with getlocalization?

**Comment by johnjohndoe** [comment]
I am not sure I understand your question. XLIFF is a localization tool:

* http://developer.android.com/distribute/tools/localization-checklist.html

**Comment by willlunniss** [comment]
GetLocalization is the transition service that we use, my only thought before merging this is to check that GetLocalization supports it. I was hoping that you might have used it so could confirm that it works. 

I'll upload a test string to check that it understands it properly.

**Comment by johnjohndoe** [comment]
Ah okay. No, I never used the service.

**Comment by willlunniss** [comment]
Seemed to work OK so merging.

**Comment by johnjohndoe** [comment]
Please note that I am happy to rebase a branch at any time to allow a clean merge aka. linear history. Feel free to rebase yourself.

**Comment by vkotovv** [comment]
@willlunniss btw, Crowdin is mentioned as tool for translating in [Readme](https://github.com/AndlyticsProject/andlytics/blob/dev/README.md) - "Translations should be done via crowdin.net". Is it a mistake?

**Comment by willlunniss** [comment]
@vkotovv My mistake, you are right @AndyScherzinger moved it.

@AndyScherzinger can you put the account details for Crowdin in the shared dropbox. And then shutdown the getlocalization account?

**Comment by willlunniss** [comment]
Removed from getlocalization and added a link to crowdin

**Comment by AndyScherzinger** [comment]
@willlunniss I put the login on Dropbox, and I also made @nelenkov a Manager of the crowdin project for Andlytics.

**Pull request merged**
