### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by casolorz**
Fix for null pointer.

### CODE REVIEW

**Comment by casolorz** [comment]
Just realized I totally forgot to update the change log and version code. I'm not home anymore and tomorrow I'm going out of town. I can do it Monday.

**Comment by nelenkov** [comment]
Thanks, I'll update version number and release if it passes my 2-minute testing :)

**Comment by nelenkov** [comment]
I am still getting some errors while scrolling through comments, so maybe you can have another look?

**Comment by casolorz** [comment]
Hmm, I stopped getting errors and have been using the app but I'll take a look when I get back in town next week.

**Comment by casolorz** [comment]
Do you still have issues with it?

**Comment by nelenkov** [comment]
Hi, 

Sorry for the late reply. I think I was running an old build. I released on Sunday, should be up.

**Comment by casolorz** [comment]
OK cool. Let me know if you find any other issues.

**Pull request merged**
